/**
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Font preload hints, kept in sync with the files the script actually wrote.
 * A hand-written preload path breaks silently when a font is renamed.
 *
 *   always — every page, because it is on the LCP path
 *   hindi  — only /hi pages; the Devanagari face is ~46 KB and useless in English
 */

export const FONT_PRELOADS = {
  always: [
    "/fonts/inter-latin.woff2"
  ],
  hindi: [
    "/fonts/noto-sans-devanagari-devanagari-w400.woff2"
  ],
} as const;
